version: '3.8'

services:
  dashboard:
    build:
      context: ./apps/dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./apps/dashboard:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - core-api

  core-api:
    build:
      context: ./services/core-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=${SUPABASE_DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    volumes:
      - ./services/core-api:/app
    restart: unless-stopped

  ai-processor:
    build:
      context: ./services/ai-processor
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./services/ai-processor:/app
    restart: unless-stopped

networks:
  default:
    name: crm-res-network